language: node_js
node_js:
  - "node"
  - "8"

sudo: false

# Cache GCloud SDK between commands
cache:
  yarn: true
  directories:
    - "$HOME/google-cloud-sdk/"

# Install services
services:
  - docker

# Set env vars
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - NODE_ENV=CI

install:
  - yarn install

script:
  - yarn test
  - codecov

before_deploy:
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then
      export CLOUDSDK_CORE_DISABLE_PROMPTS=1;
      curl https://sdk.cloud.google.com | bash;
    fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl

deploy:
  - provider: script
    script: $TRAVIS_BUILD_DIR/ops/deploy.sh
    on:
      branch: master
      tags: true
      node: "8"
