kind: Service
apiVersion: v1
metadata:
  name: dblint-ui
  labels:
    app: dblint
    tier: ui
spec:
  type: NodePort
  ports:
  - port: 10080
    targetPort: http-server
    protocol: "TCP"
    name: "http"
  selector:
    app: dblint
    tier: ui
