kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: dblint-ui
  labels:
    app: dblint
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: dblint
        tier: ui
    spec:
      containers:
      - name: dblint-ui
        # Replace  with your project ID or use `make template`.
        image: us.gcr.io/[GCLOUD_PROJECT]/dblint-ui:[VERSION]
        # This setting makes nodes pull the docker image every time before
        # starting the pod. This is useful when debugging, but should be turned
        # off in production.
        imagePullPolicy: IfNotPresent
        ports:
        - name: http-server
          containerPort: 80
        env:
          - name: PROJECT_ID
            value: [GCLOUD_PROJECT]
